import React, { useState } from 'react'
import { AuthProvider, useAuth } from './auth'
import LoginPage from './pages/LoginPage'
import SignupPage from './pages/SignupPage'
import DashboardPage from './pages/DashboardPage'

// AI-generated sample rooms (see website/generate_staged.py). They illustrate
// output quality only: they are not before/after edits of a real listing photo.
const samples = [
  { id: 'living-room', label: 'Living Room', src: '/images/after/living-room.jpg' },
  { id: 'bedroom', label: 'Bedroom', src: '/images/after/bedroom.jpg' },
  { id: 'kitchen', label: 'Kitchen', src: '/images/after/kitchen.jpg' },
  { id: 'dining-room', label: 'Dining Room', src: '/images/after/dining-room.jpg' },
]

/* ─── Logo SVG ─── */
function Logo({ size = 28 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 28 28" fill="none">
      <rect width="28" height="28" rx="6" fill="#f59e0b"/>
      <path d="M8 20V8l6 12 6-12v12" stroke="#0f172a" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  )
}

/* ─── Sample image card ─── */
function SampleCard({ src, label }) {
  return (
    <figure className="sample-card">
      <img src={src} alt={`AI-generated sample: ${label}`} loading="lazy" />
      <figcaption>{label}</figcaption>
    </figure>
  )
}

/* ─── FAQ Item ─── */
function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false)
  return (
    <div className={`faq-item ${open ? 'open' : ''}`}>
      <div className="faq-q" onClick={() => setOpen(!open)}>{q}</div>
      <div className="faq-a">{a}</div>
    </div>
  )
}

/* ─── Landing Page ─── */
function LandingPage({ onLogin, onSignup }) {
  return (
    <div className="page" id="top">
      <nav className="nav">
        <div className="nav-inner">
          <a href="#top" className="nav-logo">
            <Logo />
            <span>VirtueStage</span>
          </a>
          <div className="nav-links">
            <a href="#gallery">Samples</a>
            <a href="#how">How It Works</a>
            <a href="#pricing">Pricing</a>
            <a href="#faq">FAQ</a>
            <button type="button" className="btn btn--sm btn--ghost" onClick={onLogin}>Sign In</button>
            <button type="button" className="btn btn--sm btn--primary" onClick={onSignup}>Get Started Free</button>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section className="hero">
        <div className="hero-bg" />
        <div className="hero-bg-2" />
        <div className="hero-content">
          <span className="badge">AI-Powered Virtual Staging</span>
          <h1 className="hero-title">
            Empty rooms don't sell.<br/>
            <span className="text-accent">Staged rooms do.</span>
          </h1>
          <p className="hero-sub">
            Upload a photo of an empty room, pick a design style, and get back a furnished
            version generated by an AI image model. Built for real estate listing photos.
          </p>
          <div className="hero-ctas">
            <button type="button" className="btn btn--primary btn--lg" onClick={onSignup}>Stage Your First Room Free →</button>
            <a href="#gallery" className="btn btn--ghost btn--lg">See Samples ↓</a>
          </div>
        </div>
        <div className="hero-slider">
          <SampleCard src={samples[0].src} label="AI-generated sample: modern living room" />
        </div>
      </section>

      {/* GALLERY */}
      <section id="gallery" className="gallery">
        <div className="section-header">
          <span className="badge">Samples</span>
          <h2 className="section-title">What AI staging output looks like</h2>
          <p className="section-sub">AI-generated sample rooms made during development to illustrate the output style. They are not before/after edits of real listing photos. Sign up to stage your own photo and compare before and after side by side.</p>
        </div>
        <div className="gallery-grid">
          {samples.map((room) => <SampleCard key={room.id} src={room.src} label={room.label} />)}
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section id="how" className="how">
        <div className="section-header">
          <span className="badge badge--dark">Simple Process</span>
          <h2 className="section-title light">Three steps. That's it.</h2>
        </div>
        <div className="steps-grid">
          <div className="step">
            <div className="step-num">1</div>
            <h3>Upload</h3>
            <p>Drop in a photo of your empty room. Any angle, any size.</p>
          </div>
          <div className="step-arrow">→</div>
          <div className="step">
            <div className="step-num">2</div>
            <h3>Choose Style</h3>
            <p>Pick from Modern, Scandinavian, Luxury, Bohemian, and more.</p>
          </div>
          <div className="step-arrow">→</div>
          <div className="step">
            <div className="step-num">3</div>
            <h3>Download</h3>
            <p>Compare before and after, then download the staged image.</p>
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" className="pricing">
        <div className="section-header">
          <span className="badge">Pricing</span>
          <h2 className="section-title">Start free</h2>
          <p className="section-sub">Every account gets 3 free staging credits. Paid plans are not available yet.</p>
        </div>
        <div className="pricing-grid pricing-grid--two">
          <div className="price-card price-card--featured">
            <h3>Free</h3>
            <p className="price-desc">Available now</p>
            <div className="price"><span className="price-amount">$0</span></div>
            <ul className="price-features">
              <li>✓ 3 staging credits</li>
              <li>✓ All 6 design styles</li>
              <li>✓ Re-stage a photo in another style</li>
              <li>✓ Multi-angle room projects</li>
            </ul>
            <button type="button" className="btn btn--primary btn--full" onClick={onSignup}>Get Started Free</button>
          </div>
          <div className="price-card price-card--soon">
            <div className="price-badge">Coming soon</div>
            <h3>Pro</h3>
            <p className="price-desc">For active agents</p>
            <div className="price"><span className="price-amount">$29</span><span className="price-unit">/month (planned)</span></div>
            <ul className="price-features">
              <li>Unlimited stagings</li>
              <li>Higher resolution output</li>
              <li>Priority processing</li>
            </ul>
            <button type="button" className="btn btn--outline btn--full" disabled>Not available yet</button>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="faq">
        <div className="section-header">
          <span className="badge">FAQ</span>
          <h2 className="section-title">Frequently asked questions</h2>
        </div>
        <FAQItem q="How does it work?" a="Your photo is sent to Google's Gemini image model with a detailed, style-specific prompt that asks it to add furniture and decor while keeping the walls, floors, windows and lighting unchanged." />
        <FAQItem q="How realistic are the staged images?" a="Results are often convincing but not perfect. AI image models can occasionally alter architectural details or produce odd furniture, so review every image before using it." />
        <FAQItem q="How long does it take to stage a room?" a="Usually well under a few minutes. Time depends on the image model and photo size. The dashboard shows progress while it works." />
        <FAQItem q="Can I use the images in listings?" a="Check your MLS rules. Most require that virtually staged photos are clearly disclosed as such." />
        <FAQItem q="What if I don't like the result?" a="Re-stage the same photo in a different style from the results page. Each generation uses one credit." />
        <FAQItem q="Can I stage furnished rooms?" a="VirtueStage works best with empty or mostly empty rooms. For furnished rooms, results may vary as the AI may blend new furniture with existing items." />
      </section>

      {/* CTA */}
      <section className="cta">
        <div className="cta-inner">
          <h2>Ready to sell faster?</h2>
          <p>Stage your first room free. No credit card required.</p>
          <button className="btn btn--primary btn--lg" onClick={onSignup}>Get Started Free →</button>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="footer">
        <div className="footer-inner">
          <div className="footer-brand">
            <span className="nav-logo" style={{ fontSize: '1.1rem' }}>
              <Logo size={24} />
              VirtueStage
            </span>
            <p>AI virtual staging for real estate listing photos.</p>
          </div>
          <div className="footer-links">
            <div><h4>Product</h4><a href="#gallery">Samples</a><a href="#how">How It Works</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></div>
          </div>
        </div>
        <div className="footer-bottom"><p>&copy; 2026 VirtueStage</p></div>
      </footer>
    </div>
  )
}

/* ─── App Router ─── */
function AppRouter() {
  const { user, loading } = useAuth()
  const [page, setPage] = useState('landing')

  if (loading) return <div className="auth-page"><div className="spinner" /></div>

  if (user && (page === 'dashboard' || page === 'login' || page === 'signup')) {
    return <DashboardPage onLanding={() => setPage('landing')} />
  }

  if (page === 'login') return <LoginPage onSwitch={() => setPage('signup')} />
  if (page === 'signup') return <SignupPage onSwitch={() => setPage('login')} />

  return <LandingPage onLogin={() => setPage('login')} onSignup={() => setPage('signup')} />
}

function App() {
  return (
    <AuthProvider>
      <AppRouter />
    </AuthProvider>
  )
}

export default App
